# .github/workflows/ollama.yml
name: ollama
on: push

jobs:
  ollama:
    runs-on: ubuntu-latest

    steps:
      - name: Install ollama
        run: curl -fsSL https://ollama.com/install.sh | bash

      - name: Run LLM
        run: ollama run llama3.2 'What is a large language model?'
